name: AptyNodeUtilities
on:
  push:
    branches:
      - development
      - rc**
      - feature/**/*
  pull_request:
    branches:
      - development
      - rc**
      - feature/**/*
jobs:
  rules:
    name: Rules
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.validations.outputs.branch_name }}
    steps:
      - name: Fetch Branch Name
        uses: aptyInc/gha-branch-name@master
        id: validations

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: rules
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Caching node modules
        id: AptyNodeUtilities
        uses: actions/cache@v2
        with:
          path: "./node_modules"
          key: node-modules-${{ hashFiles('./package.json') }}

      - name: Install Deps
        if: steps.AptyNodeUtilities.outputs.cache-hit != 'true'
        run: sudo npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
